--Q11
1. SELECT COUNT() FROM STUDENT;
2. SELECT AVG(MARKS) AVG_MARKS FROM STUDENT;
3. SELECT MAX(MARKS) MAX_MARKS FROM STUDENT;
--Q12
SELECT DEPARTMENT, AVG(MARKS) AS AVG_DEPT_MARKS
FROM EMPLOYEE
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(MARKS) AS AVG_DEPT_MARKS
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(MARKS) > 75;
--Q13
SELECT * FROM ONLINE
UNION
SELECT * FROM OFFLINE;

SELECT * FROM ONLINE
UNION ALL
SELECT * FROM OFFLINE;

SELECT * FROM ONLINE
INTERSECT
SELECT * FROM OFFLINE;

SELECT * FROM ONLINE
MINUS
SELECT * FROM OFFLINE;
--Q14
1.
SELECT S.SNAME, B.BNAME
FROM SAILORS S
JOIN RESERVES R
ON R.SID = S.SID
JOIN BOATS B
ON R.BID = B.BID;

SELECT S.SNAME, B.BNAME
FROM SAILORS S, RESERVERS R, BOATS B
WHERE R.SID = S.SID AND R.BID = B.BID;

2. 
SELECT S.SNAME, B.COLOR
FROM SAILORS S
JOIN RESERVES R
ON R.SID = S.SID
JOIN BOATS B
ON R.BID = B.BID
WHERE B.COLOR = 'RED';

3.
SELECT S.SNAME, S.SID
FROM SAILORS S
WHERE S.SID NOT IN (
    SELECT R.SID
    FROM RESERVES R
);

4. 
SELECT S.SNAME, B.BNAME
FROM SAILORS S
JOIN RESERVES R
ON R.SID = S.SID
JOIN BOATS B
ON B.BID = R.BID
WHERE S.SNAME = 'Ram';